config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  resources :questions do
    resources :answers
  end

  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      resources :interests, only: [:create, :destroy]
    end
  end

  root to: "welcome#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_many :answers, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_and_belongs_to_many :topics
  has_and_belongs_to_many :interests,
                          :class_name => 'Topic',
                          :join_table => 'topics_users',
                          :foreign_key => 'topic_id',
                          :association_foreign_key => 'user_id'

  has_many :questions
  has_many :answers

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy


  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  def answers
    # we can a custom call to all answers here
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(text_value: answer_params[:text_value], user_id: current_user.id, question_id: @question.id)
    redirect_to question_path(@question)
   end

  private

  def answer_params
    params.require(:answer).permit(:text_value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up)
    devise_parameter_sanitizer.permit(:account_update)
  end

end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  def create
    debugger
    question = Question.find(params[:question_id])
    topic = Topic.find(params[:topic_id])
    if topic.present?
      current_user.interests << topic
    end

    respond_to do |format|
      format.html { redirect_to question_path(question) }
      format.js
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  skip_before_action :authenticate_user!, :only => [:show]

  def index
    @questions = current_user.questions
  end

  def show
    @question = Question.find(params[:id])
    @user = @question.user
    if user_signed_in?
      @is_current_user = current_user?(@user)
    end
  end

  def new
    @question = Question.new
  end

  def create
    topic = Topic.where(text_value: params[:topic]).first
    @question = Question.new(text_value: question_params[:text_value], topic_id: topic.id, user_id: current_user.id)
    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  private

  def question_params
    params.require(:question).permit(:text_value, :topic)
  end

  def current_user?(user)
    user == current_user
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    #redirect_to user
    #ajaxify
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  
  def index
    @questions = Question.all
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoraApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/questions/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary follow_user" %>
<% end %>

app/views/questions/_follow_form.html.erb
<% if user_signed_in? %>
  <% unless @is_current_user %>
    <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
    </div>
    <%= render 'follow_topic' %>
  <% end %>
<% end %>

app/views/questions/_follow_topic.html.erb
<%= unless current_user.topics.include?(question.topic) %>
  <%= form_tag(interests_path(current_user)) do %>
    <div><%= hidden_field_tag :topic_id, @question.topic.id %></div>
    <div><%= hidden_field_tag :question_id, @question.id %></div>
    <%= submit_tag "Follow_topic", class: "btn btn-primary follow_topic" %>
  <% end %>
<% end %>

app/views/questions/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/questions/index.html.erb
<h1>All questions of user <%= current_user.email %></h1>
<%= link_to 'create new question', new_question_path %>
<table>
  <tr>
    <th>Question</th>
    <th>Topic</th>
    <th></th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= question.text_value %></td>
      <td><%= question.topic.text_value %></td>
      <td><%= link_to 'Show', question_path(question) %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= form_with(model: @question, local: true) do |form| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :text_value %><br>
    <%= form.text_field :text_value %>
  </p>

  <%= select_tag "topic", options_for_select([['entertainment' , 'entertainment'], ['sports', 'sports']]) %>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Question_text:</strong>
  <%= @question.text_value %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @question.topic.text_value %>
</p>

<h2>Answers</h2>
 <% @question.answers.each do |answer| %>
   <p class="answer">
      <strong>Answer:</strong>
      <%= answer.text_value %>
   </p>
  <% end %>

<h2>Answer this questions:</h2>
<%= form_for([@question, @question.answers.build]) do |f| %>
<p>
  <%= f.label :text_value %><br>
  <%= f.text_field :text_value %>
</p>
 <p>
  <%= f.submit %>
 </p>
<% end %>


<%= render 'follow_form' %>



<%= link_to 'Back', questions_path %>

app/views/relationships/create.js.erb
document.getElementById("follow_form").innerHTML = "<%= escape_javascript(render('questions/unfollow')) %>";

app/views/relationships/destroy.js.erb
document.getElementById("follow_form").innerHTML = "<%= escape_javascript(render('questions/follow')) %>";

app/views/welcome/index.html.erb
<%= link_to_if(current_user.nil?, "Login", new_user_session_path, class: 'btn btn-primary m-5') do
          link_to('Sign out',  destroy_user_session_path, :method => 'delete', class: 'btn btn-danger m-5')
      end%>
============================

<h1>Quora Home</h1>
<p>Questions here</p>

<% if current_user %>
    <h5><%= current_user.email %></h5>
<%end%>

<h1>All questions</h1>
<%= link_to 'create new question', new_question_path %>
<table>
  <tr>
    <th>Question</th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= link_to question.text_value, question_path(question), class: "question" %></td>
    </tr>
  <% end %>
</table>